# Drop database
[confirm("WARNING: are you sure you want to completely remove the database?")]
@drop *args:
    #!/usr/bin/env nu
    .environments/sql/scripts/drop.nu {{ args }}

# Inspect the database
@inspect *args:
    .environments/sql/scripts/inspect.nu {{ args }}

# Migrate the database
@migrate *args:
    .environments/sql/scripts/migrate.nu {{ args }}

# Query the database
@query *args:
    .environments/sql/scripts/query.nu {{ args }}

# Seed the database
@seed *args:
    .environments/sql/scripts/seed.nu {{ args }}

# Select items from the database
@select *args:
    .environments/sql/scripts/select.nu {{ args }}

# Start docker daemon and postgresql server
@start *args:
    .environments/sql/scripts/start.nu {{ args }}

# Stop docker daemon and postgresql server
@stop *args:
    .environments/sql/scripts/stop.nu {{ args }}

# List table names
@tables *args:
    .environments/sql/scripts/tables.nu {{ args }}
