{
  config,
  lib,
  pkgs,
  ...
}: {
  packages = [pkgs.taplo];

  tasks = let
    # TODO: filter to only include files in active environments
    files = baseName:
      builtins.toJSON (map (file: {
          inherit file;
          environment = baseNameOf (dirOf file);
        })
        (builtins.filter
          (file: (baseNameOf file) == baseName)
          (lib.filesystem.listFilesRecursive ./src)));
  in {
    # TODO: should this remove the comments, keep only unique entries and sort?
    "environments:gitignore" = {
      # TODO: can this be autogenerated for all tasks and merged in below?
      # ditto for package?
      before = ["devenv:enterShell"];

      exec =
        # nusehll
        ''
          def gitignores [] {
            "${files ".gitignore"}"
            | from json
          }
        ''
        + builtins.readFile ./src/tasks/gitignore.nu;

      package = pkgs.nushell;
    };

    "environments:helix" = {
      before = ["devenv:enterShell"];

      # TODO: this one doesn't require the environment name along with the
      # files--should there be a way to grab just the files?
      exec =
        # nushell
        ''
          def language-configurations [] {
            "${files "languages.toml"}"
            | from json
          }
        ''
        + builtins.readFile ./src/tasks/helix.nu;

      package = pkgs.nushell;
    };

    "environments:just" = {
      before = ["devenv:enterShell"];

      exec =
        # nushell
        ''
          def default-justfile [] {
            open "${./src/default/Justfile}"
          }

          def aliases [] {
            [
              {
                environment: javascript

                aliases: (
                  "${builtins.toJSON config.outputs.javascript.aliases}"
                  | from json
                )
              }

              {
                environment: python

                aliases: (
                  "${builtins.toJSON config.outputs.python.aliases}"
                  | from json
                )
              }
            ]
          }

          def modules [] {
            [
              documentation
              environments
              git
              javascript
              just
              markdown
              nix
              python
              yaml
            ]
          }
        ''
        + builtins.readFile ./src/tasks/just.nu;

      package = pkgs.nushell;
    };
  };
}
