[[language]]
auto-format = true
name = "just"

[language.formatter]
args = ["--justfile", "/dev/stdin", "--dump"]
command = "just"

[[language]]
auto-format = true
name = "markdown"

[language.formatter]
args = [".md"]
command = "prettierd"

[[language]]
auto-format = true
name = "nix"

[language.formatter]
command = "alejandra"

[[language]]
auto-format = true
name = "toml"

[language.formatter]
args = ["format", "-"]
command = "taplo"
