[[language]]
name = "javascript"
auto-format = true

[language.formatter]
command = "biome"
args = ["format", "--stdin-file-path", "buffer.js"]

[[language]]
name = "jsx"
auto-format = true

[language.formatter]
command = "biome"
args = ["format", "--stdin-file-path", "buffer.jsx"]

[[language]]
name = "python"
auto-format = true

[language.formatter]
command = "ruff"
args = ["format", "-"]
