set working-directory := ".."

# View help text
@help *args:
    ./scripts/java/help.nu {{ args }}

# Remove compiled files
@clean *args:
    ./scripts/java/clean.nu {{ args }}

# Compile
@compile *args:
    ./scripts/java/compile.nu {{ args }}

# Run
@run *args:
    ./scripts/java/run.nu {{ args }}
