set working-directory := "../.."

# View help text
@help *args:
    .environments/scripts/documentation/help.nu {{ args }}

# Open a pre-configured development environment
@dev *args: open
    .environments/scripts/documentation/dev.nu {{ args }}

# Serve documentation files and recompile on changes
@serve *args: open
    .environments/scripts/documentation/serve.nu {{ args }}

[private]
open:
    open http://localhost:3000/
