set working-directory := "../.."

# View help text
@help *args:
    .environments/environments/scripts/help.nu {{ args }}

# Generate dynamic values for README and documentation
@generate-text *args:
    .environments/environments/scripts/generate-text.nu {{ args }}

# Reload environment
@reload *args:
    .environments/environments/scripts/reload.nu {{ args }}

# Set all environment nushell files as executable
@set-executable *args:
    .environments/environments/scripts/set-executable.nu {{ args }}

# Sort environment .gitignore files
@sort-gitignores *args:
    .environments/environments/scripts/sort-gitignores.nu {{ args }}

# Update init flake
@update *args:
    .environments/environments/scripts/update.nu {{ args }}

alias up := update
