set working-directory := "../.."

# View help text
@help *args:
    .environments/environments/scripts/help.nu {{ args }}

# Run pre-commit hooks
@check *args:
    .environments/environments/scripts/check.nu {{ args }}

# Update README
@generate-readme *args:
    .environments/environments/scripts/generate-readme.nu {{ args }}

# Update init flake and pre-commit hooks
@update *args:
    .environments/environments/scripts/update.nu {{ args }}

alias up := update

# Reload environment
@reload *args:
    .environments/environments/scripts/reload.nu {{ args }}

# Set all environment nushell files as executable
@set-executable *args:
    .environments/environments/scripts/set-executable.nu {{ args }}

# Sort environment .gitignore files
@sort-gitignores *args:
    .environments/environments/scripts/sort-gitignores.nu {{ args }}
