Style/FrozenStringLiteralComment:
  Enabled: No
Metrics/BlockLength:
  Enabled: No
Metrics/MethodLength:
  Enabled: No
Style/Documentation:
  Enabled: No
Style/StringLiterals:
  EnforcedStyle: double_quotes
