set dotenv-load := true
set working-directory := "../.."

# View help text
@help *args:
    .environments/scripts/zola/help.nu {{ args }}

# Serve the site
@start *args:
    .environments/scripts/zola/start.nu {{ args }}
