set working-directory := "../.."

# View help text
@help *args:
    .environments/javascript/scripts/help.nu {{ args }}

# Format javascript files
@format *args:
    .environments/javascript/scripts/format.nu {{ args }}

alias fmt := format

# Lint javascript files
@lint *args:
    .environments/javascript/scripts/lint.nu {{ args }}
