set dotenv-load := true
set working-directory := "../.."

# View help text
@help *args:
    .environments/zola/scripts/help.nu {{ args }}

# Serve the site
@start *args:
    .environments/zola/scripts/start.nu {{ args }}
