set working-directory := "../.."

# View help text
@help *args:
    .environments/scripts/c/help.nu {{ args }}

# Remove compiled files
@clean *args:
    .environments/scripts/c/clean.nu {{ args }}

# Compile
@compile *args:
    .environments/scripts/c/compile.nu {{ args }}

# Run
@run *args:
    .environments/scripts/c/run.nu {{ args }}
