set working-directory := ".."

# View help text
@help *args:
    ./scripts/c/help.nu {{ args }}

# Remove compiled files
@clean *args:
    ./scripts/c/clean.nu {{ args }}

# Compile
@compile *args:
    ./scripts/c/compile.nu {{ args }}

# Run
@run *args:
    ./scripts/c/run.nu {{ args }}
