set working-directory := "../.."

# View help text
@help *args:
    .environments/typst/scripts/help.nu {{ args }}

# Compile file
@compile *args:
    typst compile {{ args }}

# List available fonts
@fonts *args:
    typst fonts {{ args }}

# Watch file and recompile on changes
@watch *args:
    .environments/typst/scripts/watch.nu {{ args }}
