set working-directory := ".."

# View help text
@help *recipe:
    ./scripts/tree-sitter/help.nu {{ recipe }}

# Generate parser
@generate:
    ./scripts/tree-sitter/generate.nu

# Install dependencies
@install:
    ./scripts/tree-sitter/install.nu

# Parse file
parse +file:
    ./scripts/tree-sitter/parse.nu

# Test parser
test *name:
    ./scripts/tree-sitter/test.nu

# Highlight file
highlight *file:
    ./scripts/tree-sitter/highlight.nu

# Open file
open *file:
    ./scripts/tree-sitter/open.nu

# Copy queries to helix directory
install-queries:
    ./scripts/tree-sitter/install-queries.nu

# Add the grammar to helix
@install-grammar: && install-queries
    ./scripts/tree-sitter/install-grammar.nu

# Report states
report-states *rule:
    ./scripts/tree-sitter/report-states.nu
