set working-directory := "../.."

# View help text
@help *args:
    .environments/scripts/tree-sitter/help.nu {{ args }}

# Generate parser
@generate:
    .environments/scripts/tree-sitter/generate.nu

# Install dependencies
@install:
    .environments/scripts/tree-sitter/install.nu

# Parse file
parse *args:
    .environments/scripts/tree-sitter/parse.nu {{ args }}

# Test parser
test *args:
    .environments/scripts/tree-sitter/test.nu {{ args }}

# Highlight file
highlight *args:
    .environments/scripts/tree-sitter/highlight.nu {{ args }}

# Open file
open *args:
    .environments/scripts/tree-sitter/open.nu {{ args }}

# Copy queries to helix directory
install-queries:
    .environments/scripts/tree-sitter/install-queries.nu

# Add the grammar to helix
@install-grammar: && install-queries
    .environments/scripts/tree-sitter/install-grammar.nu

# Report states
report-states *args:
    .environments/scripts/tree-sitter/report-states.nu {{ args }}
